service: video-streaming-backend

frameworkVersion: '3.40.0'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: production
    FRONTEND_URL: ${env:FRONTEND_URL, 'https://your-frontend-domain.com'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:CreateBucket
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:ListBucket
            - s3:PutBucketTagging
            - s3:GetBucketTagging
          Resource: 
            - "arn:aws:s3:::video-streaming-backend-*"
            - "arn:aws:s3:::video-streaming-backend-*/*"



functions:
  api:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
    timeout: 30
    memorySize: 512
    environment:
      NODE_ENV: production

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true 